version: "2"
run:
  tests: false
  timeout: 5m
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - revive
    - gocritic
    - gosec
    - errorlint
    - prealloc
    - dupl
  exclusions:
    rules:
      - text: "package-comments: should have a package comment"
        linters:
          - revive
formatters:
  enable:
    - gofmt
    - goimports